---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: "Delete databases: {{ item }}"
  community.mysql.mysql_db:
    name: "{{ item }}"
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
  run_once: true
