---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Import vars
  ansible.builtin.import_tasks: import-vars.yml

- name: Import tasks to setup dependencies
  ansible.builtin.import_tasks: setup-dependencies.yml

- name: Import tasks to install MariaDB
  ansible.builtin.import_tasks: install-mariadb.yml

- name: Import tasks to configure MariaDB
  ansible.builtin.import_tasks: configure-mariadb.yml

- name: Import tasks to create database
  ansible.builtin.include_tasks: create-database.yml
  loop: "{{ mariadb_databases }}"

- name: Import tasks to delete database
  ansible.builtin.include_tasks: delete-database.yml
  loop: "{{ mariadb_databases_absent }}"
